Cargo.toml
=> chore: Bump up version

Cargo.toml, README.md, src/chain_verifier.rs
=> chore: Merge 'develop' into 'master'

Cargo.toml, src/chain_verifier.rs, src/lib.rs, src/primitives/environment.rs, src/primitives/response_body_v2_decoded_payload.rs, src/primitives/summary.rs, src/signed_data_verifier.rs
Implement Signed data verifier
Tests
N/A
=> feat: Signed data verifier

Cargo.toml, README.md
=> chore: Release v0.3.0

Cargo.toml, README.md
=> chore: Release v0.3.1

Cargo.toml, README.md
=> chore: Release v0.4.0

README.md
Update Verification Usage example
Update Verification Usage example
=> chore: Update Verification Usage example

.github/workflows/rust.yml
=> chore: Create rust.yml

src/primitives/jws_transaction_decoded_payload.rs
Pretty self-explanatory I think, it works for me now.
=> fix: Fix transaction fields serde names

src/signed_data_verifier.rs
https://github.com/namecare/app-store-server-library-rust/issues/22
Tests
N/A
=> feat: Verify and decode signed renewal info

src/primitives/data.rs
Add `status` field into `Data` struct.
N/A
N/A
=> feat: Add status field into data struct

Cargo.toml, src/promotional_offer_signature_creator.rs
Update dependencies and bump up version.
Tests
N/A
=> chore: Update deps

src/primitives/jws_transaction_decoded_payload.rs, src/primitives/mod.rs, src/primitives/offer_discount_type.rs
Reflect App Store Server API v1.10 changes.
Tests
N/A
=> feat: App Store Server API v1.10

Cargo.toml, src/primitives/account_tenure.rs, src/primitives/app_transaction.rs, src/primitives/auto_renew_status.rs, src/primitives/consumption_status.rs, src/primitives/delivery_status.rs, src/primitives/expiration_intent.rs, src/primitives/extend_reason_code.rs, src/primitives/jws_renewal_info_decoded_payload.rs, src/primitives/jws_transaction_decoded_payload.rs, src/primitives/lifetime_dollars_purchased.rs, src/primitives/lifetime_dollars_refunded.rs, src/primitives/offer_type.rs, src/primitives/order_lookup_status.rs, src/primitives/platform.rs, src/primitives/play_time.rs, src/primitives/price_increase_status.rs, src/primitives/revocation_reason.rs, src/primitives/status.rs, src/primitives/user_status.rs
Deserialization issues
Tests
N/A
=> fix: Deserialization issues

src/signed_data_verifier.rs
Decode and verify `AppTransaction`.
Tests
N/A
=> feature: Decode and verify app transaction

src/primitives/jws_transaction_decoded_payload.rs
Support App Store Server API v1.10.1
=> feat: Support App Store Server API v1.10.1

assets/signedExternalPurchaseTokenNotification.json, assets/signedExternalPurchaseTokenSandboxNotification.json, src/primitives/external_purchase_token.rs, src/primitives/mod.rs, src/primitives/notification_type_v2.rs, src/primitives/response_body_v2_decoded_payload.rs, src/primitives/subtype.rs, src/signed_data_verifier.rs
Support App Store Server Notifications v2.10
=> feat: Support App Store Server Notifications v2.10

assets/signedConsumptionRequestNotification.json, src/api_client.rs, src/primitives/consumption_request.rs, src/primitives/consumption_request_reason.rs, src/primitives/data.rs, src/primitives/error_payload.rs, src/primitives/mod.rs, src/primitives/refund_preference.rs, src/signed_data_verifier.rs
Add support for App Store Server API v1.11 and App Store Server Notifications v2.11
=> feat: Add support for App Store Server API v1.11 and App Store Server Notifications v2.11

Cargo.toml, README.md, assets/signedConsumptionRequestNotification.json, src/api_client.rs, src/primitives/consumption_request.rs, src/primitives/consumption_request_reason.rs, src/primitives/data.rs, src/primitives/environment.rs, src/primitives/error_payload.rs, src/primitives/mod.rs, src/primitives/notification_history_response.rs, src/primitives/notification_type_v2.rs, src/primitives/order_lookup_response.rs, src/primitives/refund_history_response.rs, src/primitives/refund_preference.rs, src/primitives/subscription_group_identifier_item.rs, src/primitives/subtype.rs, src/signed_data_verifier.rs
=> chore: Release v2.1.0

Cargo.toml, README.md
=> chore: Release 2.2.0

Cargo.toml, README.md
=> chore: Release 2.3.0

Cargo.toml, README.md
=> chore: Release 2.3.1

assets/appTransaction.json, assets/signedRenewalInfo.json, assets/signedTransaction.json, src/primitives/app_transaction.rs, src/primitives/error_payload.rs, src/primitives/jws_renewal_info_decoded_payload.rs, src/primitives/jws_transaction_decoded_payload.rs, src/primitives/mod.rs, src/primitives/purchase_platform.rs, src/signed_data_verifier.rs
=> Add support for App Store Server API v1.15

Cargo.toml
=> chore: Update libs

src/jws_signature_creator.rs, src/lib.rs
=> feat: Implement JWSSignatureCreator

Cargo.toml, README.md
=> chore: Prepare for release v3.0.0

Cargo.toml, README.md
=> chore: Prepare for release v3.1.0

Cargo.toml
=> chore: Prepare for release v3.1.1

Cargo.toml, README.md
=> chore: Prepare for release v3.2.0

src/chain_verifier.rs, src/chain_verifier_ocsp.rs, src/signed_data_verifier.rs, tests/chain_verifier.rs, tests/chain_verifier_ocsp.rs, tests/signed_data_verifier.rs
=> refactor: Introduce ChainVerifier struct

Cargo.toml, src/primitives/advanced_commerce/mod.rs, src/primitives/advanced_commerce/refund.rs, src/primitives/advanced_commerce_renewal_info.rs, src/primitives/advanced_commerce_renewal_item.rs, src/primitives/advanced_commerce_transaction_info.rs, src/primitives/advanced_commerce_transaction_item.rs, src/primitives/jws_renewal_info_decoded_payload.rs, src/primitives/jws_transaction_decoded_payload.rs, src/primitives/mod.rs
=> feat(assa): Add support for Advanced Commerce

Cargo.toml, README.md, src/api_client/api_client.rs
=> chore: Prepare for release
